#!/usr/bin/env python3
"""OpenSTA utilities for Discovery platform.

Provides:
  - SDC auto-generation from Verilog netlists
  - STA report parsing
  - CLI entry points for shell script integration
"""
import os
import sys
import re
import argparse
from typing import Dict, List, Optional, Any


# ============= SDC GENERATION =============

def detect_clock_ports(netlist_path: str) -> List[str]:
    """Detect likely clock ports from a Verilog netlist.

    Heuristic: look for input ports with 'clk' or 'clock' in the name.
    """
    clocks = []
    if not os.path.exists(netlist_path):
        return clocks

    with open(netlist_path, 'r', errors='replace') as f:
        content = f.read()

    # Match input port declarations
    # Patterns: "input clk;" or "input wire clk;" or "input clk,"
    input_ports = re.findall(
        r'\binput\s+(?:wire\s+)?(?:\[\d+:\d+\]\s+)?(\w+)',
        content
    )

    for port in input_ports:
        lower = port.lower()
        if any(kw in lower for kw in ['clk', 'clock']):
            clocks.append(port)

    return clocks


def detect_io_ports(netlist_path: str) -> Dict[str, List[str]]:
    """Detect input and output ports from a Verilog netlist."""
    result = {"inputs": [], "outputs": []}
    if not os.path.exists(netlist_path):
        return result

    with open(netlist_path, 'r', errors='replace') as f:
        content = f.read()

    result["inputs"] = re.findall(
        r'\binput\s+(?:wire\s+)?(?:\[\d+:\d+\]\s+)?(\w+)',
        content
    )
    result["outputs"] = re.findall(
        r'\boutput\s+(?:wire\s+|reg\s+)?(?:\[\d+:\d+\]\s+)?(\w+)',
        content
    )
    return result


def generate_sdc(netlist_path: str, clk_port: str = "clk",
                 clk_period: float = 10.0) -> str:
    """Generate SDC timing constraints for a netlist.

    Args:
        netlist_path: Path to gate-level Verilog netlist.
        clk_port: Clock port name.
        clk_period: Clock period in nanoseconds.

    Returns:
        SDC content as string.
    """
    io = detect_io_ports(netlist_path)
    detected_clocks = detect_clock_ports(netlist_path)

    # Use detected clock if the specified one doesn't exist in inputs
    if clk_port not in io["inputs"] and detected_clocks:
        clk_port = detected_clocks[0]

    # Non-clock inputs for set_input_delay
    non_clk_inputs = [p for p in io["inputs"] if p != clk_port]

    delay_factor = 0.2
    delay = clk_period * delay_factor
    transition = 0.1  # ns

    lines = [
        "# Auto-generated SDC timing constraints",
        "# Generated by OpenSTA Discovery agent",
        "#",
        "# ASSUMPTIONS:",
        f"#   - Clock port: {clk_port}",
        f"#   - Clock period: {clk_period} ns ({1000.0/clk_period:.1f} MHz)",
        f"#   - Input/output delay: {delay_factor*100:.0f}% of clock period ({delay:.2f} ns)",
        f"#   - Input transition: {transition} ns",
        "#   - No multi-cycle paths or false paths assumed",
        "#",
        "",
        f"set period {clk_period}",
        f'create_clock -period $period [get_ports {clk_port}]',
        "",
    ]

    if non_clk_inputs:
        # Group inputs for set_input_delay
        input_list = " ".join(non_clk_inputs)
        lines.append(f"set delay [expr $period * {delay_factor}]")
        lines.append(f'set_input_delay $delay -clock {clk_port} {{{input_list}}}')
    else:
        lines.append(f"# No non-clock inputs detected")

    if io["outputs"]:
        lines.append(f'set_output_delay [expr $period * {delay_factor}] -clock {clk_port} [all_outputs]')
    else:
        lines.append("# No outputs detected")

    lines.append("")
    lines.append(f"set_input_transition {transition} [all_inputs]")
    lines.append("")

    return "\n".join(lines)


# ============= REPORT PARSING =============

def parse_sta_report(log_path: str) -> str:
    """Parse OpenSTA log output into a formatted report.

    Args:
        log_path: Path to the STA log file.

    Returns:
        Formatted report string.
    """
    if not os.path.exists(log_path):
        return f"ERROR: Log file not found: {log_path}"

    with open(log_path, 'r', errors='replace') as f:
        content = f.read()

    lines = []
    lines.append("=" * 60)
    lines.append("OPENSTA STATIC TIMING ANALYSIS REPORT")
    lines.append("=" * 60)
    lines.append("")

    # Extract key sections from the log
    sections = {
        "Setup Timing": extract_section(content, "Setup Timing (Max Delay)", "Hold Timing (Min Delay)"),
        "Hold Timing": extract_section(content, "Hold Timing (Min Delay)", "Worst Slack"),
        "Worst Slack": extract_section(content, "Worst Slack", "Timing Summary"),
        "Timing Summary": extract_section(content, "Timing Summary", "Check Setup"),
    }

    # Extract worst slack values
    setup_slack = extract_value(content, r'Setup \(max\):\s*([-\d.]+)')
    hold_slack = extract_value(content, r'Hold\s+\(min\):\s*([-\d.]+)')

    # Summary box
    lines.append("--- Timing Summary ---")
    if setup_slack is not None:
        status = "MET" if setup_slack >= 0 else "VIOLATED"
        lines.append(f"  Setup (worst slack): {setup_slack:.4f} ns  [{status}]")
    if hold_slack is not None:
        status = "MET" if hold_slack >= 0 else "VIOLATED"
        lines.append(f"  Hold  (worst slack): {hold_slack:.4f} ns  [{status}]")
    lines.append("")

    # Include each section
    for name, section_text in sections.items():
        if section_text:
            lines.append(f"--- {name} ---")
            lines.append(section_text.strip())
            lines.append("")

    # If no structured sections found, include the raw log
    if not any(sections.values()):
        lines.append("--- Raw STA Output ---")
        # Filter out noise lines
        for line in content.split('\n'):
            stripped = line.strip()
            if stripped and not stripped.startswith('OpenSTA'):
                lines.append(stripped)

    return "\n".join(lines)


def extract_section(content: str, start_marker: str, end_marker: str) -> Optional[str]:
    """Extract text between two markers in the log."""
    start_esc = re.escape(start_marker)
    end_esc = re.escape(end_marker)
    pattern = f"=== {start_esc} ===(.*?)(?:=== {end_esc} ===|$)"
    m = re.search(pattern, content, re.DOTALL)
    if m:
        return m.group(1).strip()
    return None


def extract_value(content: str, pattern: str) -> Optional[float]:
    """Extract a float value matching a regex pattern."""
    m = re.search(pattern, content)
    if m:
        try:
            return float(m.group(1))
        except ValueError:
            return None
    return None


# ============= CLI ENTRY POINTS =============

def cli_generate_sdc():
    """CLI: Generate SDC from netlist."""
    parser = argparse.ArgumentParser(description="Generate SDC constraints")
    parser.add_argument("--netlist", required=True, help="Path to Verilog netlist")
    parser.add_argument("--clk-port", default="clk", help="Clock port name")
    parser.add_argument("--clk-period", type=float, default=10.0, help="Clock period (ns)")
    parser.add_argument("--output", required=True, help="Output SDC file path")
    args = parser.parse_args(sys.argv[2:])

    sdc = generate_sdc(args.netlist, args.clk_port, args.clk_period)
    with open(args.output, 'w') as f:
        f.write(sdc)
    print(f"SDC written to {args.output}")


def cli_parse_report():
    """CLI: Parse STA log into formatted report."""
    if len(sys.argv) < 3:
        print("Usage: python3 sta_utils.py parse-report <log_file>", file=sys.stderr)
        sys.exit(1)
    log_path = sys.argv[2]
    report = parse_sta_report(log_path)
    print(report)


if __name__ == "__main__":
    if len(sys.argv) >= 2:
        cmd = sys.argv[1]
        if cmd == "generate-sdc":
            cli_generate_sdc()
        elif cmd == "parse-report":
            cli_parse_report()
        else:
            print(f"Unknown command: {cmd}", file=sys.stderr)
            print("Available: generate-sdc, parse-report", file=sys.stderr)
            sys.exit(1)
    else:
        print("OpenSTA utilities. Use: python3 sta_utils.py <command>")
        print("Commands: generate-sdc, parse-report")
