#!/usr/bin/env python3
"""04b_train_ensemble_v2.py - Phase 1D, iteration 2.

Adds physicochemical features + hyperparameter sweep on top of the v1
baseline (MAE 0.57). Goal: MAE on log10(GWP100) <= 0.4.

Pipeline:
  1. Load gwp_train.csv + features.csv (joined on isomeric SMILES).
  2. Build chemprop datapoints with `x_d` extra molecular descriptors.
  3. Hyperparameter sweep: hidden_dim x depth x dropout (3x3x3 = 27 configs)
     using 5-fold Tanimoto-clustered CV. Pick best by mean CV MAE.
  4. Retrain final 5-model ensemble on full train set with best config.
  5. Save: ensemble .pt, hyperopt_results.csv, manifest.json, parity plot.

Inputs (mounted from depends_on Phase 1C tanimoto split job + features
generated by the failed scaffold-split job which still has features.csv):
  /input/processed/gwp_train.csv
  /input/processed/gwp_holdout_external.csv
  /deps/<features_job>/processed/features.csv  -- if features.csv was on
       a different parent, but in our case the Phase 1C split's input was
       gwp_resolved_v2.csv which doesn't have features. We re-compute
       features here directly from RDKit (faster than chaining).
"""

import os, sys, json, logging, time, traceback, itertools
from pathlib import Path
import pandas as pd
import numpy as np

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
log = logging.getLogger("train2")

INPUT_DIR = Path("/input")
OUTPUT_DIR = Path("/output")
MODELS_DIR = OUTPUT_DIR / "models" / "ensemble_v2"
SWEEP_DIR = OUTPUT_DIR / "sweep"
CV_DIR = OUTPUT_DIR / "cv"
MODELS_DIR.mkdir(parents=True, exist_ok=True)
SWEEP_DIR.mkdir(parents=True, exist_ok=True)
CV_DIR.mkdir(parents=True, exist_ok=True)

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
log.info(f"PyTorch: {torch.__version__}")
log.info(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    log.info(f"CUDA device: {torch.cuda.get_device_name(0)}")

ACCELERATOR = "gpu" if torch.cuda.is_available() else "cpu"
DEVICES = 1 if torch.cuda.is_available() else "auto"

import chemprop
from chemprop import data, featurizers, models, nn as cpnn
from lightning import pytorch as pl

from rdkit import Chem, DataStructs, RDLogger
RDLogger.DisableLog("rdApp.*")
from rdkit.Chem import AllChem, Crippen, Descriptors, rdMolDescriptors
from rdkit.ML.Cluster import Butina


# ============================================================
# Step 1: Load + compute features
# ============================================================
log.info("=" * 70)
log.info("Step 1: Load data + compute physicochemical features")
log.info("=" * 70)

train_df = pd.read_csv(INPUT_DIR / "processed" / "gwp_train.csv")
holdout_df = pd.read_csv(INPUT_DIR / "processed" / "gwp_holdout_external.csv")
log.info(f"  train: {len(train_df)} rows  holdout: {len(holdout_df)} rows (RESERVED)")

train_df["log10_lifetime"] = np.log10(train_df["lifetime_years"].clip(lower=1e-6))


def count_bond_to(mol, atomic_num):
    n = 0
    for bond in mol.GetBonds():
        a, b = bond.GetBeginAtom(), bond.GetEndAtom()
        if (a.GetAtomicNum() == 6 and b.GetAtomicNum() == atomic_num) or \
           (b.GetAtomicNum() == 6 and a.GetAtomicNum() == atomic_num):
            n += 1
    return n


# Feature names + computation function
FEATURE_NAMES = [
    "n_C_F_bonds", "n_C_Cl_bonds", "n_C_Br_bonds", "n_C_I_bonds",
    "n_F", "n_Cl", "n_Br", "n_I", "n_H", "n_C", "n_O", "n_N", "n_S", "n_Si",
    "mw", "n_heavy_atoms", "n_rotatable_bonds", "n_rings", "n_aromatic_rings",
    "logp_crippen", "mr_crippen", "tpsa", "n_h_donors", "n_h_acceptors",
    "fraction_csp3", "n_unsaturated_bonds", "halogen_fraction",
]


def compute_features(smi):
    mol = Chem.MolFromSmiles(smi)
    if mol is None:
        return None
    f = {}
    f["n_C_F_bonds"] = count_bond_to(mol, 9)
    f["n_C_Cl_bonds"] = count_bond_to(mol, 17)
    f["n_C_Br_bonds"] = count_bond_to(mol, 35)
    f["n_C_I_bonds"] = count_bond_to(mol, 53)
    f["n_F"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "F")
    f["n_Cl"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "Cl")
    f["n_Br"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "Br")
    f["n_I"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "I")
    f["n_H"] = sum(a.GetTotalNumHs() for a in mol.GetAtoms())
    f["n_C"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "C")
    f["n_O"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "O")
    f["n_N"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "N")
    f["n_S"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "S")
    f["n_Si"] = sum(1 for a in mol.GetAtoms() if a.GetSymbol() == "Si")
    f["mw"] = float(Descriptors.MolWt(mol))
    f["n_heavy_atoms"] = mol.GetNumHeavyAtoms()
    f["n_rotatable_bonds"] = rdMolDescriptors.CalcNumRotatableBonds(mol)
    f["n_rings"] = rdMolDescriptors.CalcNumRings(mol)
    f["n_aromatic_rings"] = rdMolDescriptors.CalcNumAromaticRings(mol)
    f["logp_crippen"] = float(Crippen.MolLogP(mol))
    f["mr_crippen"] = float(Crippen.MolMR(mol))
    f["tpsa"] = float(rdMolDescriptors.CalcTPSA(mol))
    f["n_h_donors"] = rdMolDescriptors.CalcNumHBD(mol)
    f["n_h_acceptors"] = rdMolDescriptors.CalcNumHBA(mol)
    f["fraction_csp3"] = float(rdMolDescriptors.CalcFractionCSP3(mol))
    f["n_unsaturated_bonds"] = sum(
        1 for b in mol.GetBonds() if b.GetBondType() != Chem.BondType.SINGLE
    )
    nh = f["n_F"] + f["n_Cl"] + f["n_Br"] + f["n_I"]
    f["halogen_fraction"] = float(nh) / max(f["n_heavy_atoms"], 1)
    return f


feat_rows = []
for smi in train_df["isomeric_smiles"]:
    f = compute_features(smi)
    feat_rows.append([f[n] for n in FEATURE_NAMES] if f else [0.0] * len(FEATURE_NAMES))
features_arr = np.array(feat_rows, dtype=np.float32)
log.info(f"  features shape: {features_arr.shape}")
log.info(f"  feature ranges (first 5): " + ", ".join(
    f"{n}=[{features_arr[:,i].min():.1f},{features_arr[:,i].max():.1f}]"
    for i, n in enumerate(FEATURE_NAMES[:5])
))

# Standardize features (zero mean, unit variance)
feat_mean = features_arr.mean(axis=0)
feat_std = features_arr.std(axis=0) + 1e-8
features_arr_z = (features_arr - feat_mean) / feat_std
log.info(f"  z-scored features (mean={features_arr_z.mean():.3f}, std={features_arr_z.std():.3f})")


# ============================================================
# Step 2: 5-fold Tanimoto-clustered split
# ============================================================
log.info("=" * 70)
log.info("Step 2: Compute 5-fold Tanimoto-clustered splits")
log.info("=" * 70)

gen = AllChem.GetMorganGenerator(radius=2, fpSize=2048)
fps = [gen.GetFingerprint(Chem.MolFromSmiles(s)) for s in train_df["isomeric_smiles"]]
n = len(fps)
dists = []
for i in range(1, n):
    sims = DataStructs.BulkTanimotoSimilarity(fps[i], fps[:i])
    dists.extend(1.0 - np.array(sims))
clusters = list(Butina.ClusterData(dists, n, 0.35, isDistData=True))
clusters = sorted(clusters, key=lambda c: -len(c))
log.info(f"  {len(clusters)} Butina clusters (cutoff=0.35)")

NFOLDS = 5
folds = [[] for _ in range(NFOLDS)]
fold_sizes = [0] * NFOLDS
for ci, members in enumerate(clusters):
    f = int(np.argmin(fold_sizes))
    folds[f].extend(members)
    fold_sizes[f] += len(members)
fold_assign = np.zeros(n, dtype=int)
for fi, members in enumerate(folds):
    for m in members:
        fold_assign[m] = fi
log.info(f"  fold sizes: {[len(f) for f in folds]}")


# ============================================================
# Step 3: Build datapoints with extra molecular descriptors (x_d)
# ============================================================
log.info("=" * 70)
log.info("Step 3: Build chemprop datapoints with x_d extra descriptors")
log.info("=" * 70)


def make_datapoints(df, feat_arr_z):
    """Build chemprop MoleculeDatapoints with [log10_gwp, log10_lifetime] + x_d features."""
    datapoints = []
    for i, smi in enumerate(df["isomeric_smiles"].values):
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        y = np.array([
            df.iloc[i]["log10_gwp100"],
            df.iloc[i]["log10_lifetime"] if not np.isnan(df.iloc[i]["log10_lifetime"]) else 0.0,
        ], dtype=np.float32)
        x_d = feat_arr_z[i].astype(np.float32)
        dp = data.MoleculeDatapoint.from_smi(smi, y=y, weight=1.0, x_d=x_d)
        datapoints.append(dp)
    return datapoints


all_dps = make_datapoints(train_df, features_arr_z)
log.info(f"  built {len(all_dps)} datapoints with x_d shape {features_arr_z.shape[1]}")


# ============================================================
# Step 4: Build / train helper with hyperparams
# ============================================================
def build_mpnn_with_xd(n_tasks=2, hidden_dim=200, depth=3, dropout=0.0,
                       ffn_hidden_dim=200, ffn_num_layers=2, n_extra_features=0):
    """Build chemprop MPNN with extra x_d features mixed into FFN."""
    mp = cpnn.BondMessagePassing(d_h=hidden_dim, depth=depth, dropout=dropout)
    agg = cpnn.NormAggregation()
    # FFN input is hidden_dim (from MPNN) + n_extra_features (from x_d)
    ffn = cpnn.RegressionFFN(
        n_tasks=n_tasks,
        input_dim=hidden_dim + n_extra_features,
        hidden_dim=ffn_hidden_dim,
        n_layers=ffn_num_layers,
        dropout=dropout,
    )
    # X_d transformation: identity (already z-scored)
    X_d_transform = None
    model = models.MPNN(
        mp, agg, ffn, batch_norm=False,
        metrics=[cpnn.metrics.MAE(), cpnn.metrics.RMSE()],
        X_d_transform=X_d_transform,
    )
    return model


def train_one(train_dps, val_dps, hidden_dim, depth, dropout, max_epochs=80, patience=15, seed=0):
    """Train one model; returns predictions + metrics."""
    pl.seed_everything(seed, workers=True)

    featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()
    tr_dataset = data.MoleculeDataset(train_dps, featurizer=featurizer)
    val_dataset = data.MoleculeDataset(val_dps, featurizer=featurizer)
    scaler = tr_dataset.normalize_targets()
    val_dataset.normalize_targets(scaler)

    tr_loader = data.build_dataloader(tr_dataset, batch_size=32, num_workers=0, shuffle=True)
    val_loader = data.build_dataloader(val_dataset, batch_size=64, num_workers=0, shuffle=False)

    model = build_mpnn_with_xd(
        n_tasks=2,
        hidden_dim=hidden_dim,
        depth=depth,
        dropout=dropout,
        ffn_hidden_dim=hidden_dim,
        ffn_num_layers=2,
        n_extra_features=features_arr_z.shape[1],
    )

    callbacks = [
        pl.callbacks.EarlyStopping(monitor="val_loss", patience=patience, mode="min", verbose=False),
    ]
    trainer = pl.Trainer(
        accelerator=ACCELERATOR,
        devices=DEVICES,
        max_epochs=max_epochs,
        callbacks=callbacks,
        logger=False,
        enable_checkpointing=False,
        enable_progress_bar=False,
        enable_model_summary=False,
    )
    trainer.fit(model, tr_loader, val_loader)

    val_preds = trainer.predict(model, val_loader)
    val_preds = torch.cat(val_preds, dim=0).numpy()
    val_preds_unscaled = scaler.inverse_transform(val_preds)
    val_y_unscaled = np.array([dp.y for dp in val_dps])
    return model, val_preds_unscaled, val_y_unscaled, scaler


# ============================================================
# Step 5: Hyperparameter sweep with 5-fold CV
# ============================================================
log.info("=" * 70)
log.info("Step 5: Hyperparameter sweep (3 hidden x 3 depth x 3 dropout = 27 configs)")
log.info("=" * 70)

HIDDEN_DIMS = [200, 300, 500]
DEPTHS = [3, 4, 5]
DROPOUTS = [0.0, 0.1, 0.2]

cv_targets_gwp = train_df["log10_gwp100"].values
cv_targets_lt = train_df["log10_lifetime"].values
cv_targets_lt_mask = ~train_df["lifetime_years"].isna().values

sweep_results = []
t_start = time.time()
total_configs = len(HIDDEN_DIMS) * len(DEPTHS) * len(DROPOUTS)
config_idx = 0

for hidden_dim, depth, dropout in itertools.product(HIDDEN_DIMS, DEPTHS, DROPOUTS):
    config_idx += 1
    cfg_name = f"h{hidden_dim}_d{depth}_p{dropout}"
    log.info(f"\n--- Config {config_idx}/{total_configs}: {cfg_name} ---")
    cv_preds_gwp = np.zeros(n)
    cv_preds_lt = np.zeros(n)
    fold_metrics = []
    cfg_t0 = time.time()
    try:
        for fi in range(NFOLDS):
            val_idx = np.where(fold_assign == fi)[0]
            tr_idx = np.where(fold_assign != fi)[0]
            tr_dps = [all_dps[i] for i in tr_idx]
            val_dps = [all_dps[i] for i in val_idx]
            _, val_preds, val_y, _ = train_one(
                tr_dps, val_dps,
                hidden_dim=hidden_dim, depth=depth, dropout=dropout,
                max_epochs=80, patience=15, seed=fi,
            )
            cv_preds_gwp[val_idx] = val_preds[:, 0]
            cv_preds_lt[val_idx] = val_preds[:, 1]
            mae_g = float(np.mean(np.abs(val_preds[:, 0] - val_y[:, 0])))
            fold_metrics.append({"fold": fi, "mae_gwp": mae_g})
        # Aggregate
        mae_g_all = float(np.mean(np.abs(cv_preds_gwp - cv_targets_gwp)))
        rmse_g_all = float(np.sqrt(np.mean((cv_preds_gwp - cv_targets_gwp) ** 2)))
        r2_g_all = float(1.0 - np.sum((cv_preds_gwp - cv_targets_gwp) ** 2) / np.sum((cv_targets_gwp - cv_targets_gwp.mean()) ** 2))
        mae_lt_all = float(np.mean(np.abs(cv_preds_lt[cv_targets_lt_mask] - cv_targets_lt[cv_targets_lt_mask])))
        cfg_elapsed = time.time() - cfg_t0
        log.info(f"  {cfg_name}: MAE_gwp={mae_g_all:.3f} R2={r2_g_all:.3f} MAE_lt={mae_lt_all:.3f} time={cfg_elapsed:.0f}s")
        sweep_results.append({
            "config": cfg_name,
            "hidden_dim": hidden_dim,
            "depth": depth,
            "dropout": dropout,
            "mae_log10_gwp": mae_g_all,
            "rmse_log10_gwp": rmse_g_all,
            "r2_log10_gwp": r2_g_all,
            "mae_log10_lifetime": mae_lt_all,
            "elapsed_seconds": cfg_elapsed,
            "fold_metrics": fold_metrics,
        })
        # Incremental save
        with (SWEEP_DIR / "sweep_progress.json").open("w") as f:
            json.dump({
                "completed": config_idx, "total": total_configs,
                "elapsed": time.time() - t_start,
                "results": sweep_results,
            }, f, indent=2)
    except Exception as e:
        log.error(f"  CONFIG FAILED: {cfg_name}: {type(e).__name__}: {e}")
        traceback.print_exc()
        sweep_results.append({
            "config": cfg_name, "hidden_dim": hidden_dim, "depth": depth, "dropout": dropout,
            "error": f"{type(e).__name__}: {e}",
        })

sweep_total_elapsed = time.time() - t_start
log.info(f"\nSWEEP COMPLETE in {sweep_total_elapsed:.0f}s")

# Save sweep CSV
sweep_df = pd.DataFrame([r for r in sweep_results if "error" not in r])
sweep_df = sweep_df.sort_values("mae_log10_gwp")
sweep_df.to_csv(SWEEP_DIR / "hyperopt_results.csv", index=False)

log.info(f"\nTop 5 configs by MAE log10(GWP):")
for _, row in sweep_df.head(5).iterrows():
    log.info(f"  {row['config']}: MAE={row['mae_log10_gwp']:.3f} R2={row['r2_log10_gwp']:.3f} MAE_lt={row['mae_log10_lifetime']:.3f}")

# Pick best
best = sweep_df.iloc[0]
best_cfg = {
    "hidden_dim": int(best["hidden_dim"]),
    "depth": int(best["depth"]),
    "dropout": float(best["dropout"]),
    "cv_mae_log10_gwp": float(best["mae_log10_gwp"]),
    "cv_rmse_log10_gwp": float(best["rmse_log10_gwp"]),
    "cv_r2_log10_gwp": float(best["r2_log10_gwp"]),
    "cv_mae_log10_lifetime": float(best["mae_log10_lifetime"]),
}
log.info(f"\nBEST CONFIG: hidden={best_cfg['hidden_dim']} depth={best_cfg['depth']} dropout={best_cfg['dropout']}  MAE_gwp={best_cfg['cv_mae_log10_gwp']:.3f}")


# ============================================================
# Step 6: Train final 5-model ensemble with best config
# ============================================================
log.info("=" * 70)
log.info("Step 6: Train final 5-model ensemble on full train set")
log.info("=" * 70)

ensemble_meta = []
for seed in range(5):
    log.info(f"\n--- Ensemble member {seed+1}/5 (seed={seed}) ---")
    t0 = time.time()
    pl.seed_everything(seed, workers=True)

    featurizer = featurizers.SimpleMoleculeMolGraphFeaturizer()
    full_dataset = data.MoleculeDataset(all_dps, featurizer=featurizer)
    scaler = full_dataset.normalize_targets()
    full_loader = data.build_dataloader(full_dataset, batch_size=32, num_workers=0, shuffle=True)

    model = build_mpnn_with_xd(
        n_tasks=2,
        hidden_dim=best_cfg["hidden_dim"],
        depth=best_cfg["depth"],
        dropout=best_cfg["dropout"],
        ffn_hidden_dim=best_cfg["hidden_dim"],
        ffn_num_layers=2,
        n_extra_features=features_arr_z.shape[1],
    )
    trainer = pl.Trainer(
        accelerator=ACCELERATOR,
        devices=DEVICES,
        max_epochs=60,
        logger=False,
        enable_checkpointing=False,
        enable_progress_bar=False,
        enable_model_summary=False,
    )
    trainer.fit(model, full_loader)
    elapsed = time.time() - t0
    model_path = MODELS_DIR / f"model_{seed}.pt"
    torch.save({
        "model_state_dict": model.state_dict(),
        "scaler_mean": scaler.mean_.tolist(),
        "scaler_scale": scaler.scale_.tolist(),
        "feat_mean": feat_mean.tolist(),
        "feat_std": feat_std.tolist(),
        "feature_names": FEATURE_NAMES,
        "n_tasks": 2,
        **best_cfg,
    }, model_path)
    log.info(f"  saved {model_path.name} in {elapsed:.1f}s")
    ensemble_meta.append({"seed": seed, "model_path": str(model_path.relative_to(OUTPUT_DIR)), "train_seconds": elapsed})


# ============================================================
# Step 7: Save manifest + summary
# ============================================================
manifest = {
    "version": "v2_features_hyperopt",
    "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "n_models": 5,
    "n_train": int(len(train_df)),
    "n_holdout_reserved": int(len(holdout_df)),
    "tasks": ["log10_gwp100", "log10_lifetime"],
    "best_config": best_cfg,
    "feature_names": FEATURE_NAMES,
    "n_features": len(FEATURE_NAMES),
    "feat_mean": feat_mean.tolist(),
    "feat_std": feat_std.tolist(),
    "training": {
        "max_epochs_cv": 80,
        "max_epochs_final": 60,
        "early_stopping_patience": 15,
        "batch_size": 32,
        "accelerator": ACCELERATOR,
        "chemprop_version": chemprop.__version__,
        "torch_version": torch.__version__,
    },
    "members": ensemble_meta,
    "sweep_total_elapsed": sweep_total_elapsed,
    "sweep_n_configs": total_configs,
}
with (MODELS_DIR / "manifest.json").open("w") as f:
    json.dump(manifest, f, indent=2, default=str)


# ============================================================
# Step 8: Sweep heatmap visualization
# ============================================================
fig, ax = plt.subplots(figsize=(8, 6))
# Build a hidden_dim x depth heatmap, taking best dropout per cell
sweep_df_clean = sweep_df.copy()
pivot = sweep_df_clean.pivot_table(
    index="depth", columns="hidden_dim", values="mae_log10_gwp", aggfunc="min"
)
im = ax.imshow(pivot.values, cmap="viridis_r", aspect="auto")
ax.set_xticks(range(len(pivot.columns)))
ax.set_xticklabels(pivot.columns)
ax.set_yticks(range(len(pivot.index)))
ax.set_yticklabels(pivot.index)
ax.set_xlabel("hidden_dim")
ax.set_ylabel("depth")
ax.set_title("Hyperopt: best CV MAE log10(GWP100) per (hidden, depth)")
for i in range(len(pivot.index)):
    for j in range(len(pivot.columns)):
        v = pivot.values[i, j]
        ax.text(j, i, f"{v:.3f}", ha="center", va="center", color="white" if v > pivot.values.mean() else "black")
plt.colorbar(im, ax=ax, label="MAE log10(GWP)")
plt.tight_layout()
plt.savefig(SWEEP_DIR / "hyperopt_heatmap.png", dpi=120, bbox_inches="tight")
plt.close()


final_summary = {
    "n_train": int(len(train_df)),
    "n_holdout_reserved_untouched": int(len(holdout_df)),
    "n_features": len(FEATURE_NAMES),
    "ensemble_size": 5,
    "accelerator": ACCELERATOR,
    "best_config": best_cfg,
    "v1_baseline_mae": 0.570,
    "v2_with_features_and_hyperopt_mae": best_cfg["cv_mae_log10_gwp"],
    "improvement_pct": float(100 * (0.570 - best_cfg["cv_mae_log10_gwp"]) / 0.570),
    "target_mae_met": best_cfg["cv_mae_log10_gwp"] < 0.4,
    "sweep_total_minutes": round(sweep_total_elapsed / 60, 1),
    "sweep_top5": sweep_df.head(5)[["config", "mae_log10_gwp", "r2_log10_gwp", "mae_log10_lifetime"]].to_dict("records"),
}
with (OUTPUT_DIR / "final_results.json").open("w") as f:
    json.dump({"status": "completed", "summary": final_summary}, f, indent=2, default=str)

log.info("=" * 70)
log.info("DONE")
for k, v in final_summary.items():
    log.info(f"  {k}: {v}")
